version: "3.7"

services:
  rabbitmq:
    image: rabbitmq:management-alpine
    ports:
      - 15672:15672
    networks:
      - mongo_cluster

  chatserver:
    container_name: chatserver
    image: chatserver
    env_file:
      - ./apps/chat_server/.env
    build:
      target: development
      context: .
      dockerfile: ./apps/chat_server/Dockerfile
    ports:
      - 9223:9229
    networks:
      - mongo_cluster
    command: npm run start:debug chat_server
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - mongodb-primary
      - mongodb-secondary
      - mongodb-arbiter
      - rabbitmq

  gateway:
    container_name: gateway
    image: gateway
    env_file:
      - ./apps/gateway/.env
    build:
      target: development
      context: .
      dockerfile: ./apps/gateway/Dockerfile
    ports:
      - 3001:3001
      - 9222:9229
    networks:
      - mongo_cluster
    command: npm run start:debug gateway
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - chatserver
      - statistics
      - rabbitmq

  statistics:
    container_name: statistics
    image: statistics
    env_file:
      - ./apps/statistics/.env
    build:
      target: development
      context: .
      dockerfile: ./apps/statistics/Dockerfile
    ports:
      - 9224:9229
    networks:
      - mongo_cluster
    command: npm run start:debug statistics
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - mongodb-primary
      - mongodb-secondary
      - mongodb-arbiter
      - rabbitmq

  mongodb-primary:
    image: docker.io/bitnami/mongodb:5.0
    environment:
      - MONGODB_ADVERTISED_HOSTNAME=mongodb-primary
      - MONGODB_REPLICA_SET_MODE=primary
      - MONGODB_ROOT_PASSWORD=password123
      - MONGODB_REPLICA_SET_KEY=replicasetkey123
    volumes:
      - "mongodb_master_data:/bitnami/mongodb"
    ports:
      - 27017:27017
    networks:
      - mongo_cluster

  mongodb-secondary:
    image: docker.io/bitnami/mongodb:5.0
    depends_on:
      - mongodb-primary
    environment:
      - MONGODB_ADVERTISED_HOSTNAME=mongodb-secondary
      - MONGODB_REPLICA_SET_MODE=secondary
      - MONGODB_INITIAL_PRIMARY_HOST=mongodb-primary
      - MONGODB_INITIAL_PRIMARY_ROOT_PASSWORD=password123
      - MONGODB_REPLICA_SET_KEY=replicasetkey123
    networks:
      - mongo_cluster

  mongodb-arbiter:
    image: docker.io/bitnami/mongodb:5.0
    depends_on:
      - mongodb-primary
    environment:
      - MONGODB_ADVERTISED_HOSTNAME=mongodb-arbiter
      - MONGODB_REPLICA_SET_MODE=arbiter
      - MONGODB_INITIAL_PRIMARY_HOST=mongodb-primary
      - MONGODB_INITIAL_PRIMARY_ROOT_PASSWORD=password123
      - MONGODB_REPLICA_SET_KEY=replicasetkey123
    networks:
      - mongo_cluster

networks:
  mongo_cluster:
    name: mongo_cluster

volumes:
  mongodb_master_data:
    driver: local
