version: "3.7"

services:
  chatserver:
    container_name: chatserver
    image: chatserver
    env_file:
      - docker.env
    environment:
      - NODE_ENV=development
    build:
      target: development
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 3000:3000
      - 9229:9229
    networks:
      - chat_server_mongoCluster
    command: npm run start:debug
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules

  mongo-express:
    image: mongo-express
    container_name: "mongo-express"
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_ROOT_USERNAME}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_ROOT_PASSWORD}
      ME_CONFIG_MONGODB_URL: ${DATABASE_URL}
    networks:
      - chat_server_mongoCluster

networks:
  chat_server_mongoCluster:
    external: true
