import { PrismaClient, Prisma } from "@prisma/client"

const prisma = new PrismaClient()

const userData: Prisma.CarCreateInput[] = [
    {
        city_mpg: 17,
        class: "small sport utility vehicle",
        combination_mpg: 20,
        cylinders: 4,
        displacement: 2,
        drive: "4wd",
        fuel_type: "gas",
        highway_mpg: 24,
        make: "land rover",
        model: "lr2",
        transmission: "a",
        year: 2015
    },
    {
        city_mpg: 15,
        class: "standard sport utility vehicle",
        combination_mpg: 16,
        cylinders: 6,
        displacement: 3,
        drive: "4wd",
        fuel_type: "gas",
        highway_mpg: 19,
        make: "land rover",
        model: "lr4",
        transmission: "a",
        year: 2015
    },
    {
        city_mpg: 14,
        class: "standard sport utility vehicle",
        combination_mpg: 16,
        cylinders: 8,
        displacement: 5,
        drive: "4wd",
        fuel_type: "gas",
        highway_mpg: 19,
        make: "land rover",
        model: "range rover sport",
        transmission: "a",
        year: 2015
    },
    {
        city_mpg: 14,
        class: "standard sport utility vehicle",
        combination_mpg: 16,
        cylinders: 8,
        displacement: 5,
        drive: "4wd",
        fuel_type: "gas",
        highway_mpg: 19,
        make: "land rover",
        model: "range rover ffv",
        transmission: "a",
        year: 2015
    },
    {
        city_mpg: 14,
        class: "standard sport utility vehicle",
        combination_mpg: 16,
        cylinders: 8,
        displacement: 5,
        drive: "4wd",
        fuel_type: "gas",
        highway_mpg: 19,
        make: "land rover",
        model: "range rover l ffv",
        transmission: "a",
        year: 2015
    },
    {
        city_mpg: 18,
        class: "standard sport utility vehicle",
        combination_mpg: 19,
        cylinders: 4,
        displacement: 2,
        drive: "4wd",
        fuel_type: "gas",
        highway_mpg: 21,
        make: "land rover",
        model: "defender 90",
        transmission: "a",
        year: 2023
    },
    {
        city_mpg: 19,
        class: "standard sport utility vehicle",
        combination_mpg: 21,
        cylinders: 4,
        displacement: 2,
        drive: "4wd",
        fuel_type: "gas",
        highway_mpg: 22,
        make: "land rover",
        model: "discovery",
        transmission: "a",
        year: 2023
    },
    {
        city_mpg: 19,
        class: "standard sport utility vehicle",
        combination_mpg: 22,
        cylinders: 6,
        displacement: 3,
        drive: "4wd",
        fuel_type: "gas",
        highway_mpg: 25,
        make: "land rover",
        model: "discovery mhev",
        transmission: "a",
        year: 2023
    },
    {
        city_mpg: 17,
        class: "standard sport utility vehicle",
        combination_mpg: 18,
        cylinders: 4,
        displacement: 2,
        drive: "4wd",
        fuel_type: "gas",
        highway_mpg: 20,
        make: "land rover",
        model: "defender 110",
        transmission: "a",
        year: 2023
    },
    {
        city_mpg: 18,
        class: "standard sport utility vehicle",
        combination_mpg: 20,
        cylinders: 6,
        displacement: 3,
        drive: "4wd",
        fuel_type: "gas",
        highway_mpg: 23,
        make: "land rover",
        model: "defender 110 mhev",
        transmission: "a",
        year: 2023
    },
    {
        city_mpg: 28,
        class: "compact car",
        combination_mpg: 31,
        cylinders: 4,
        displacement: 1.6,
        drive: "fwd",
        fuel_type: "gas",
        highway_mpg: 35,
        make: "hyundai",
        model: "veloster",
        transmission: "a",
        year: 2016
    },
    {
        city_mpg: 27,
        class: "compact car",
        combination_mpg: 30,
        cylinders: 4,
        displacement: 1.6,
        drive: "fwd",
        fuel_type: "gas",
        highway_mpg: 34,
        make: "hyundai",
        model: "veloster",
        transmission: "m",
        year: 2016
    },
    {
        city_mpg: 24,
        class: "midsize car",
        combination_mpg: 27,
        cylinders: 4,
        displacement: 2,
        drive: "fwd",
        fuel_type: "gas",
        highway_mpg: 32,
        make: "hyundai",
        model: "elantra gt",
        transmission: "m",
        year: 2016
    },
    {
        city_mpg: 24,
        class: "midsize car",
        combination_mpg: 27,
        cylinders: 4,
        displacement: 2,
        drive: "fwd",
        fuel_type: "gas",
        highway_mpg: 32,
        make: "hyundai",
        model: "elantra gt",
        transmission: "a",
        year: 2016
    },
    {
        city_mpg: 26,
        class: "compact car",
        combination_mpg: 29,
        cylinders: 4,
        displacement: 1.6,
        drive: "fwd",
        fuel_type: "gas",
        highway_mpg: 32,
        make: "hyundai",
        model: "veloster",
        transmission: "a",
        year: 2016
    },
    {
        city_mpg: 80,
        class: "small sport utility vehicle",
        combination_mpg: 76,
        drive: "4wd",
        fuel_type: "electricity",
        highway_mpg: 72,
        make: "jaguar",
        model: "i-pace",
        transmission: "a",
        year: 2020
    },
    {
        city_mpg: 132,
        class: "small sport utility vehicle",
        combination_mpg: 120,
        drive: "fwd",
        fuel_type: "electricity",
        highway_mpg: 108,
        make: "hyundai",
        model: "kona electric",
        transmission: "a",
        year: 2020
    },
    {
        city_mpg: 127,
        class: "small station wagon",
        combination_mpg: 118,
        drive: "fwd",
        fuel_type: "electricity",
        highway_mpg: 108,
        make: "chevrolet",
        model: "bolt ev",
        transmission: "a",
        year: 2020
    },
    {
        city_mpg: 145,
        class: "midsize car",
        combination_mpg: 133,
        drive: "fwd",
        fuel_type: "electricity",
        highway_mpg: 121,
        make: "hyundai",
        model: "ioniq electric",
        transmission: "a",
        year: 2020
    },
    {
        city_mpg: 19,
        class: "small pickup truck",
        combination_mpg: 22,
        cylinders: 6,
        displacement: 3.5,
        drive: "fwd",
        fuel_type: "gas",
        highway_mpg: 26,
        make: "honda",
        model: "ridgeline fwd",
        transmission: "a",
        year: 2017
    },
    {
        city_mpg: 18,
        class: "standard pickup truck",
        combination_mpg: 21,
        cylinders: 6,
        displacement: 3.5,
        drive: "awd",
        fuel_type: "gas",
        highway_mpg: 25,
        make: "honda",
        model: "ridgeline awd",
        transmission: "a",
        year: 2017
    },
    {
        city_mpg: 18,
        class: "midsize car",
        combination_mpg: 21,
        cylinders: 6,
        displacement: 3.5,
        drive: "fwd",
        fuel_type: "gas",
        highway_mpg: 28,
        make: "honda",
        model: "accord",
        transmission: "m",
        year: 2017
    },
    {
        city_mpg: 21,
        class: "midsize car",
        combination_mpg: 25,
        cylinders: 6,
        displacement: 3.5,
        drive: "fwd",
        fuel_type: "gas",
        highway_mpg: 33,
        make: "honda",
        model: "accord",
        transmission: "a",
        year: 2017
    },
    {
        city_mpg: 21,
        class: "midsize car",
        combination_mpg: 24,
        cylinders: 6,
        displacement: 3.5,
        drive: "fwd",
        fuel_type: "gas",
        highway_mpg: 32,
        make: "honda",
        model: "accord",
        transmission: "a",
        year: 2017
    },
    {
        city_mpg: 23,
        class: "compact car",
        combination_mpg: 27,
        cylinders: 4,
        displacement: 2.4,
        drive: "fwd",
        fuel_type: "gas",
        highway_mpg: 33,
        make: "acura",
        model: "tlx fwd",
        transmission: "a",
        year: 2018
    },
    {
        city_mpg: 20,
        class: "compact car",
        combination_mpg: 24,
        cylinders: 6,
        displacement: 3.5,
        drive: "fwd",
        fuel_type: "gas",
        highway_mpg: 32,
        make: "acura",
        model: "tlx fwd",
        transmission: "a",
        year: 2018
    },
    {
        city_mpg: 20,
        class: "compact car",
        combination_mpg: 23,
        cylinders: 6,
        displacement: 3.5,
        drive: "fwd",
        fuel_type: "gas",
        highway_mpg: 30,
        make: "acura",
        model: "tlx fwd a-spec",
        transmission: "a",
        year: 2018
    },
    {
        city_mpg: 21,
        class: "compact car",
        combination_mpg: 24,
        cylinders: 6,
        displacement: 3.5,
        drive: "awd",
        fuel_type: "gas",
        highway_mpg: 30,
        make: "acura",
        model: "tlx awd",
        transmission: "a",
        year: 2018
    },
    {
        city_mpg: 20,
        class: "compact car",
        combination_mpg: 23,
        cylinders: 6,
        displacement: 3.5,
        drive: "awd",
        fuel_type: "gas",
        highway_mpg: 29,
        make: "acura",
        model: "tlx awd a-spec",
        transmission: "a",
        year: 2018
    },
    {
        city_mpg: 20,
        class: "compact car",
        combination_mpg: 22,
        cylinders: 4,
        displacement: 2,
        drive: "awd",
        fuel_type: "gas",
        highway_mpg: 27,
        make: "volvo",
        model: "s60 polestar awd",
        transmission: "a",
        year: 2018
    },
    {
        city_mpg: 20,
        class: "small station wagon",
        combination_mpg: 22,
        cylinders: 4,
        displacement: 2,
        drive: "awd",
        fuel_type: "gas",
        highway_mpg: 27,
        make: "volvo",
        model: "v60 polestar awd",
        transmission: "a",
        year: 2018
    },
    {
        city_mpg: 25,
        class: "compact car",
        combination_mpg: 29,
        cylinders: 4,
        displacement: 2,
        drive: "fwd",
        fuel_type: "gas",
        highway_mpg: 36,
        make: "volvo",
        model: "s60 inscription fwd",
        transmission: "a",
        year: 2018
    },
    {
        city_mpg: 25,
        class: "compact car",
        combination_mpg: 29,
        cylinders: 4,
        displacement: 2,
        drive: "fwd",
        fuel_type: "gas",
        highway_mpg: 36,
        make: "volvo",
        model: "s60 fwd",
        transmission: "a",
        year: 2018
    },
    {
        city_mpg: 22,
        class: "compact car",
        combination_mpg: 26,
        cylinders: 4,
        displacement: 2,
        drive: "awd",
        fuel_type: "gas",
        highway_mpg: 32,
        make: "volvo",
        model: "s60 awd",
        transmission: "a",
        year: 2018
    },
    {
        city_mpg: 20,
        class: "small sport utility vehicle",
        combination_mpg: 23,
        cylinders: 6,
        displacement: 3.2,
        drive: "fwd",
        fuel_type: "gas",
        highway_mpg: 29,
        make: "jeep",
        model: "cherokee fwd",
        transmission: "a",
        year: 2019
    },
    {
        city_mpg: 19,
        class: "small sport utility vehicle",
        combination_mpg: 22,
        cylinders: 6,
        displacement: 3.2,
        drive: "awd",
        fuel_type: "gas",
        highway_mpg: 27,
        make: "jeep",
        model: "cherokee 4wd",
        transmission: "a",
        year: 2019
    },
    {
        city_mpg: 18,
        class: "small sport utility vehicle",
        combination_mpg: 21,
        cylinders: 6,
        displacement: 3.2,
        drive: "4wd",
        fuel_type: "gas",
        highway_mpg: 26,
        make: "jeep",
        model: "cherokee 4wd active drive ii",
        transmission: "a",
        year: 2019
    },
    {
        city_mpg: 18,
        class: "small sport utility vehicle",
        combination_mpg: 21,
        cylinders: 6,
        displacement: 3.2,
        drive: "4wd",
        fuel_type: "gas",
        highway_mpg: 24,
        make: "jeep",
        model: "cherokee trailhawk 4wd",
        transmission: "a",
        year: 2019
    },
    {
        city_mpg: 16,
        class: "two seater",
        combination_mpg: 19,
        cylinders: 8,
        displacement: 6.2,
        drive: "rwd",
        fuel_type: "gas",
        highway_mpg: 25,
        make: "chevrolet",
        model: "corvette",
        transmission: "m",
        year: 2019
    },
    {
        city_mpg: 29,
        class: "small sport utility vehicle",
        combination_mpg: 31,
        cylinders: 4,
        displacement: 2,
        drive: "fwd",
        fuel_type: "gas",
        highway_mpg: 34,
        make: "kia",
        model: "seltos fwd",
        transmission: "a",
        year: 2021
    },
    {
        city_mpg: 25,
        class: "small sport utility vehicle",
        combination_mpg: 27,
        cylinders: 4,
        displacement: 1.6,
        drive: "awd",
        fuel_type: "gas",
        highway_mpg: 30,
        make: "kia",
        model: "seltos awd",
        transmission: "a",
        year: 2021
    },
    {
        city_mpg: 27,
        class: "small sport utility vehicle",
        combination_mpg: 29,
        cylinders: 4,
        displacement: 2,
        drive: "awd",
        fuel_type: "gas",
        highway_mpg: 31,
        make: "kia",
        model: "seltos awd",
        transmission: "a",
        year: 2021
    },
    {
        city_mpg: 19,
        class: "two seater",
        combination_mpg: 22,
        cylinders: 6,
        displacement: 3,
        drive: "rwd",
        fuel_type: "gas",
        highway_mpg: 27,
        make: "jaguar",
        model: "f-type s coupe",
        transmission: "a",
        year: 2021
    },
    {
        city_mpg: 19,
        class: "two seater",
        combination_mpg: 22,
        cylinders: 6,
        displacement: 3,
        drive: "rwd",
        fuel_type: "gas",
        highway_mpg: 27,
        make: "jaguar",
        model: "f-type s convertible",
        transmission: "a",
        year: 2021
    },
    {
        city_mpg: 19,
        class: "minivan",
        combination_mpg: 22,
        cylinders: 6,
        displacement: 3.5,
        drive: "fwd",
        fuel_type: "gas",
        highway_mpg: 28,
        make: "honda",
        model: "odyssey",
        transmission: "a",
        year: 2022
    },
    {
        city_mpg: 21,
        class: "midsize car",
        combination_mpg: 24,
        cylinders: 4,
        displacement: 2.5,
        drive: "awd",
        fuel_type: "gas",
        highway_mpg: 29,
        make: "kia",
        model: "stinger awd",
        transmission: "a",
        year: 2022
    },
    {
        city_mpg: 22,
        class: "midsize car",
        combination_mpg: 25,
        cylinders: 4,
        displacement: 2.5,
        drive: "rwd",
        fuel_type: "gas",
        highway_mpg: 32,
        make: "kia",
        model: "stinger rwd",
        transmission: "a",
        year: 2022
    },
    {
        city_mpg: 17,
        class: "midsize car",
        combination_mpg: 20,
        cylinders: 6,
        displacement: 3.3,
        drive: "awd",
        fuel_type: "gas",
        highway_mpg: 24,
        make: "kia",
        model: "stinger awd",
        transmission: "a",
        year: 2022
    },
    {
        city_mpg: 18,
        class: "midsize car",
        combination_mpg: 20,
        cylinders: 6,
        displacement: 3.3,
        drive: "rwd",
        fuel_type: "gas",
        highway_mpg: 25,
        make: "kia",
        model: "stinger rwd",
        transmission: "a",
        year: 2022
    },
    {
        city_mpg: 76,
        class: "standard sport utility vehicle",
        combination_mpg: 77,
        drive: "awd",
        fuel_type: "electricity",
        highway_mpg: 80,
        make: "bmw",
        model: "ix m60 (21 inch wheels)",
        transmission: "a",
        year: 2023
    },
    {
        city_mpg: 77,
        class: "standard sport utility vehicle",
        combination_mpg: 78,
        drive: "awd",
        fuel_type: "electricity",
        highway_mpg: 80,
        make: "bmw",
        model: "ix m60 (22 inch wheels)",
        transmission: "a",
        year: 2023
    },
    {
        city_mpg: 103,
        class: "large car",
        combination_mpg: 95,
        drive: "awd",
        fuel_type: "electricity",
        highway_mpg: 86,
        make: "genesis",
        model: "gv60 advance",
        transmission: "a",
        year: 2023
    },
    {
        city_mpg: 97,
        class: "large car",
        combination_mpg: 90,
        drive: "awd",
        fuel_type: "electricity",
        highway_mpg: 82,
        make: "genesis",
        model: "gv60 performance",
        transmission: "a",
        year: 2023
    },
    {
        city_mpg: 119,
        class: "subcompact car",
        combination_mpg: 110,
        drive: "fwd",
        fuel_type: "electricity",
        highway_mpg: 100,
        make: "mini",
        model: "cooper se hardtop 2 door",
        transmission: "a",
        year: 2023
    }
]

async function main() {
    console.log(`Start seeding ...`)
    console.log(process.env.DATABASE_URL)
    for (const u of userData) {
        const user = await prisma.car.create({
            data: u
        })
        console.log(`Created user with id: ${user.id}`)
    }
    console.log(`Seeding finished.`)
}

main()
    .then(async () => {
        await prisma.$disconnect()
    })
    .catch(async (e) => {
        console.error("Error: " + e)
        await prisma.$disconnect()
        process.exit(1)
    })
